# GitHub repository module configuration
# Generated by Azure GitHub Environment Bootstrap migration script
module "github_repository" {
  source  = "pagopa-dx/github-environment-bootstrap/github"
  version = "~> 1.0"

  repository = {
    name               = local.repository.name
    description        = local.repository.description
    topics             = local.repository.topics
    reviewers_teams    = local.repository.reviewers_teams
    app_cd_policy_tags = local.repository.app_cd_policy_tags
    environments       = ["prod"]
    jira_boards_ids    = local.repository.jira_boards_ids
  }
}
