oa3_spec: apps/licences/openapi/bff-openapi.yaml
name: licences_api_iopatente
location: Italy North
timespan: 10m
evaluation_frequency: 20 # default 10
evaluation_time_window: 40 # default 20
event_occurrences: 2 # default 1
data_source: /subscriptions/ec285037-c673-4f58-b594-d7c480da4e8b/resourceGroups/io-p-rg-external/providers/Microsoft.Network/applicationGateways/io-p-appgateway # ?
action_groups:
  - /subscriptions/ec285037-c673-4f58-b594-d7c480da4e8b/resourceGroups/io-p-itn-svc-rg-01/providers/Microsoft.Insights/actiongroups/io-p-svc-offcall-ag-01
overrides:
  hosts:
    - licences.ipatente.io.pagopa.it
