openapi: 3.0.0
info:
  title: Info Veicoli API
  description: Specifica delle API backend for frontend (BFF) per la funzionalità **I miei veicoli**.
  version: 1.0.0
servers:
  - url: http://localhost:8080

paths:
  /infoVeicoli:
    get:
      summary: Recupero di tutti i dati inerenti veicoli area privata
      operationId: getInfoVeicoli
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Veicolo"
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: Not found
        500:
          description: Internal server error

components:
  schemas:
    Veicolo:
      type: object
      required:
        - targaVeicolo
        - tipoVeicolo
      properties:
        targaVeicolo:
          description: Targa Veicolo
          type: string
        tipoVeicolo:
          $ref: "#/components/schemas/TipoVeicoloEnum"
        datiVeicolo:
          $ref: "#/components/schemas/DatiVeicolo"
        storicoRevisioni:
          type: array
          items:
            $ref: "#/components/schemas/Revisione"
        coperturaRCA:
          $ref: "#/components/schemas/CoperturaRCA"
    DatiVeicolo:
      type: "object"
      properties:
        extraMassa:
          description: |
            ### Messaggi restituiti:
            Messaggio che indica se il veicolo e' soggetto ad extra massa
            - "NPDA_EXTRAMASSA_MSG001" (Traduzione frontend ita: IL VEICOLO NON RIENTRA NELLE CONDIZIONI DI CUI ALL'ARTICOLO 116, CO.3, LETT. F), N. 2, CDS)
            - "NPDA_EXTRAMASSA_MSG002" (Il veicolo di categoria N2, alimentato con combustibile alternativo e con una massa autorizzata massima compresa tra 3.500 kg e 4.250 kg, adibito al trasporto di merci e che opera senza rimorchio, può essere condotto dai titolari di una patente di guida di categoria B rilasciata da almeno due anni.)

          type: "string"
        neopatentati:
          description: |
            ### Messaggi restituiti:
            - "NPDA_NEOPAT_MSG001" (Traduzione frontend ita: Il veicolo può essere guidato da un neopatentato.)
            - "NPDA_NEOPAT_MSG002" (Traduzione frontend ita: Il veicolo non può essere guidato da un conducente che abbia conseguito la patente da meno di un anno. Tale limite non si applica se a fianco del conducente si trova, in funzione di istruttore, persona di età non superiore a sessantacinque anni, munita di patente valida per la stessa categoria, conseguita da almeno dieci anni, ovvero valida per la categoria superiore.)
            - "NPDA_NEOPAT_MSG003" (Traduzione frontend ita: Dati tecnici mancanti.)
            - "NPDA_NEOPAT_MSG004" (Traduzione frontend ita: Dato Non Verificabile.)
          type: "string"
        classeAmbientale:
          $ref: "#/components/schemas/ClasseAmbientaleEnum"
    Revisione:
      type: "object"
      required:
        - dataRevisione
        - esitoRevisione
      properties:
        dataRevisione:
          type: "string"
        esitoRevisione:
          $ref: "#/components/schemas/EsitoRevisioneEnum"
        kmPercorsi:
          type: "number"
        kmTotali:
          type: "number"
    CoperturaRCA:
      type: object
      description: ultima assicurazione valida in corso, null se non presente
      required:
        - compagniaAssicuratrice
        - dataScadenzaCopertura
      properties:
        compagniaAssicuratrice:
          description: Indica la compagnia con cui  e' stata stipuilata la copertura RCA
          type: string
        dataScadenzaCopertura:
          description: Indica la data di scadenza della copertura RCA, comprensiva del periodo di comporto
          type: string
          format: date
    TipoVeicoloEnum:
      type: string
      description: |
        ### Tipo veicolo
        - "C" (Ciclomotore)
        - "A" (Autoveicolo)
        - "M" (Motoveicolo)
        - "R" (Rimorchio)
        - "N" (Macchina Operatrice Trainata)
        - "P" (Macchina Operatrice Semovente)
        - "U" (Macchina Agricola Semovente ad 1 asse)
        - "X" (Macchina Agricola Operatrice Trainata)
        - "Y" (Rimorchio Agricolo con Massa complessiva a pieno carico non superiore a 1,5 tonnellate)
        - "S" (Macchina Agricola Semovente munita di almeno 2 assi)
        - "T" (Rimorchio Agricolo)
        - "V" (Macchina Agricola Operatrice)
        - "E" (Autoveicolo e Rimorchio - Targhe di Prova)
        - "F" (Motoveicolo e Ciclomotore - Targhe di Prova)
        - "G" (Macchina Agricola - Targhe di Prova)
        - "H" (Macchina Operatrice - Targhe di Prova)
        - "CD" (Corpo Diplomatico - Targhe Diplomatiche)
        - "CC" (Corpo Consolare - Targhe Diplomatiche)
        - "EE" (Escursionisti Esteri - Targhe Diplomatiche)
      enum: [C, A, M, R, N, P, U, X, Y, S, T, V, E, F, G, H, CD, CC, EE]
    ClasseAmbientaleEnum:
      type: string
      description: |
        ### Messaggi restituiti:
        - EURO0
        - EURO1
        - EURO2
        - EURO3
        - EURO4
        - EURO5
        - EURO5B
        - EURO6
        - EURO6A
        - EURO6B
        - EURO6C
        - EURO6D
        - EURO6E
        - Dato non disponibile
      enum:
        [
          EURO0,
          EURO1,
          EURO2,
          EURO3,
          EURO4,
          EURO5,
          EURO5B,
          EURO6,
          EURO6A,
          EURO6B,
          EURO6C,
          EURO6D,
          EURO6E,
        ]
    EsitoRevisioneEnum:
      type: "string"
      description: |
        ### Esito revisione
        - "P" (Regolare)
        - "R" (Ripetere)
        - "S" (Sospendere)
      enum: [P, R, S]
