name: "Determine Turbo Cache Path"
description: "Determines the version of Turborepo and sets the appropriate cache path in env."

runs:
  using: "composite"
  steps:
    - name: Determine Turbo Cache Path
      shell: bash
      run: |
        TURBO_VERSION=$(yarn turbo --version)
        echo "Turbo version: $TURBO_VERSION"
        if [[ "$TURBO_VERSION" =~ ^1\..* ]]; then
          TURBO_CACHE_PATH="node_modules/.cache/turbo"
        else
          TURBO_CACHE_PATH=".turbo"
        fi
        echo "TURBO_CACHE_PATH=$TURBO_CACHE_PATH" >> $GITHUB_ENV
        echo "Using cache path: $TURBO_CACHE_PATH"
