name: Opex Dashboard vehicles openapi

# Controls when the workflow will run
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - IOPAE-1531-opex-dashboard
    paths:
      - 'apps/vehicles/openapi/bff-openapi.yaml'
      - '.github/workflows/opex_vehicles_api.yml'
      - '.opex/vehicles/**'

env:
  API_NAME: vehicles
  APP_NAME: vehicles

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-22.04
    environment: opex-prod-cd

    steps:
      - name: Checkout
        id: checkout
        # from https://github.com/actions/checkout/commits/main
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          persist-credentials: false
          fetch-depth: 0
      
      # mitigation: opex-dashboard-azure-action currently does not support .opex
      # directory parameter
      - run: |
          cp -r apps/${{ env.APP_NAME }}/.opex ./
        name: Update Path
        shell: bash

      # from https://github.com/pagopa/opex-dashboard-azure-action/
      - uses: pagopa/opex-dashboard-azure-action@3ad80a5e4a2d5a8f342615637072f21b687320ce # action v1.2.1
        with:
          environment: prod
          api-name: ${{ env.API_NAME }}
          config: .opex/${{ env.API_NAME }}/env/prod/config.yaml
          client-id: ${{ secrets.ARM_CLIENT_ID }}
          tenant-id: ${{ secrets.ARM_TENANT_ID }}
          subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          # from https://github.com/pagopa/opex-dashboard-azure-action/pkgs/container/opex-dashboard-azure-action
          docker-version: sha256:04d8ead53c772d23b094c2a395292dc159e6f2905e1b13b5f828f31eac6eb27f
